project:
  type: website
  output-dir: "."
  render: ["**/*.qmd", "README.qmd"]

website:
  repo-url: https://github.com/wagov-dtt/architecture-decision-records
  repo-actions: [edit, source]

format:
  gfm:
    output-ext: md
    variant: +yaml_metadata_block
    preserve-yaml: true
