project:
  type: book
  output-dir: _site
book:
  title: "DGOV DTT Architecture Decision Records"
  output-file: "architecture-decision-records"
  chapters:
    - index.qmd
    - architecture-principles.qmd
    - part: Development ADRs
      chapters:
        - development/003-apis.qmd
        - development/004-cicd.qmd
        - development/009-release.qmd
    - part: Operations ADRs
      chapters:
        - operations/002-workloads.qmd
        - operations/007-logging.qmd
        - operations/010-configmgmt.qmd
        - operations/014-object-backup.qmd
        - operations/017-policy-enforcement.qmd
        - operations/019-database-patterns.qmd
        - operations/020-data-governance.qmd
        - operations/021-analytics-tooling.qmd
    - part: Security ADRs
      chapters:
        - security/001-isolation.qmd
        - security/005-secrets-management.qmd
        - security/011-ai-preapproval.qmd
        - security/012-ai-sandbox.qmd
        - security/013-identity-federation.qmd
        - security/015-email-authentication.qmd
        - security/016-edge-protection.qmd
        - security/018-zero-trust-access.qmd
    - part: Reference Architectures
      chapters:
        - reference-architectures/content-management.qmd
        - reference-architectures/data-pipelines.qmd
        - reference-architectures/identity-management.qmd
        - reference-architectures/openapi-backends.qmd
    - CONTRIBUTING.md
    - glossary.qmd
format:
  html:
    toc: true
    number-sections: false
    search: true
  pdf:
    toc: true
    toc-depth: 1
    number-sections: false
    documentclass: scrbook
    classoption: [openany, oneside, fontsize=10pt]
    geometry: [margin=0.75in]
    colorlinks: true
git-hash: b4eeee0
