project:
  type: book
profile:
  group:
    - [book, gfm]
  default: book
book:
  title: "DGOV DTT Architecture Decision Records"
  output-file: "architecture-decision-records"
  # AUTOMATIC MANAGEMENT: The chapters list below is automatically updated by `just update-chapters`
  # Manual edits to the chapters section will be overwritten
  chapters:
    - index.qmd
    - architecture-principles.md
    - part: Development ADRs
      chapters:
        - development/003-apis.qmd
        - development/004-cicd.qmd
        - development/009-release.qmd
    - part: Operations ADRs
      chapters:
        - operations/002-workloads.qmd
        - operations/006-policy-enforcement.qmd
        - operations/007-logging.qmd
        - operations/010-configmgmt.qmd
        - operations/014-object-backup.qmd
        - operations/015-data-governance.qmd
        - operations/017-analytics-tooling.qmd
        - operations/018-database-patterns.qmd
    - part: Security ADRs
      chapters:
        - security/001-isolation.qmd
        - security/005-secrets-management.qmd
        - security/008-email-authentication.qmd
        - security/011-ai-governance.qmd
        - security/012-privileged-remote-access.qmd
        - security/013-identity-federation.qmd
        - security/016-edge-protection.qmd
    - part: Reference Architectures
      chapters:
        - reference-architectures/content-management.qmd
        - reference-architectures/data-pipelines.qmd
        - reference-architectures/identity-management.qmd
        - reference-architectures/openapi-backends.qmd
    - CONTRIBUTING.md
    - glossary.md
git-hash: 4c4d75e
