[book]
title = "DGOV DTT Architecture Decision Records"
authors = ["DGOV DTT"]
description = "Architecture records and current decision state to support infrastructure and platform operations"
src = "."

[build]
build-dir = "book"

[output.html]
no-section-label = true
git-repository-url = "https://github.com/wagov-dtt/architecture-decision-records"
edit-url-template = "https://github.com/wagov-dtt/architecture-decision-records/edit/main/{path}"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html.print]
enable = true
