---
title: "Glossary"
---

## Acronyms and Definitions

**ACSC** - Australian Cyber Security Centre  
**ADR** - Architecture Decision Record  
**API** - Application Programming Interface  
**ATT&CK** - Adversarial Tactics, Techniques & Common Knowledge (MITRE)  
**AWS** - Amazon Web Services  
**BIMI** - Brand Indicators for Message Identification  
**CDN** - Content Delivery Network  
**CI/CD** - Continuous Integration/Continuous Deployment  
**CNCF** - Cloud Native Computing Foundation  
**DGOV** - Office of Digital Government (Western Australia)  
**DKIM** - DomainKeys Identified Mail  
**DMARC** - Domain-based Message Authentication, Reporting and Conformance  
**DNS** - Domain Name System  
**DTT** - Digital Transformation and Technology Unit  
**EKS** - Elastic Kubernetes Service (AWS)  
**GCP** - Google Cloud Platform  
**IAM** - Identity and Access Management  
**IAP** - Identity-Aware Proxy  
**JIT** - Just-In-Time  
**OWASP** - Open Web Application Security Project  
**RDP** - Remote Desktop Protocol  
**RPO** - Recovery Point Objective  
**RTO** - Recovery Time Objective  
**SIEM** - Security Information and Event Management  
**SPF** - Sender Policy Framework  
**TLS** - Transport Layer Security  
**VPN** - Virtual Private Network  
**WAF** - Web Application Firewall
