[tools]
"cargo:mdbook-mermaid" = "latest"
"cargo:just" = "latest"
"cargo:mdbook" = "latest"
cargo-binstall = "latest"
"cargo:lychee" = "latest"
"cargo:rumdl" = "latest"

[tasks.build]
description = "Build the book"
run = "just build"

[settings]
cargo.binstall = true
experimental = true
lockfile = true
